# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-25 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mp_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
