# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set_Logged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(default=0)),
                ('set_number', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='signup.Exercise_Logged')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='signup.Exercise'),
        ),
    ]
