# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20181026_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_logged',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='set_logged',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='set_logged',
            name='seconds',
        ),
    ]
