# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20181026_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='set',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
    ]
