# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20181026_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='users_logged',
            field=models.ManyToManyField(default=None, null=True, related_name='workouts_logged', to='signup.User'),
        ),
    ]
